- name: Install k3s server
  hosts: master
  become: yes

  tasks:
    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Get node token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: token

    - name: Save token
      delegate_to: localhost
      copy:
        content: "{{ token.stdout }}"
        dest: "./node-token"